### ISSUE TITLE
Bad Request if batch is float during training.

### ISSUE THREAD

**Issue by ambitious-octopus** [ultralytics/hub-sdk#148]
### Search before asking

- [X] I have searched the HUB-SDK [issues](https://github.com/ultralytics/hub-sdk/issues) and found no similar bug report.

### HUB-SDK Component

Train, Integrations, Other

### Bug

```bash
HUB-SDK -> {'config': {'batchSize': 0.9, 'epochs': 100, 'imageSize': 640, 'patience': 100, 'device': '', 'cache': 'ram'}, 'dataset': {'name': 'coco8.yaml'}, 'lineage': {'architecture': {'name': 'yolov8n'}, 'parent': {'name': 'yolov8n.pt'}}, 'meta': {'name': 'yolov8n.pt'}}
2024-06-18 12:04:17,022 - hub_sdk.helpers.logger - ERROR - Bad Request
2024-06-18 12:04:17,022 - hub_sdk.helpers.logger - ERROR - Received no response from the server while creating the model.
```
If the batch size is a float the model is not created in hub.

### Minimal Reproducible Example

doesn't work with this:
```python
from ultralytics import YOLO, hub

HUB_KEY = ""
hub.login(HUB_KEY)

model = YOLO("yolov8n.pt")
model.train(data="coco8.yaml", batch=0.2, epochs=100)
```

works with this:

```python
from ultralytics import YOLO, hub

HUB_KEY = ""
hub.login(HUB_KEY)

model = YOLO("yolov8n.pt")
model.train(data="coco8.yaml", batch=1, epochs=100)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by sergiuwaxmann** [comment]
@ambitious-octopus Yeah, HUB doesn't support the recent `ultralytics` change for `batchSize` (can be `float`).
I will try to fix this soon - busy with other tasks at the moment.
