### ISSUE TITLE
Repo is missing CI

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub-sdk#48]
@kalenmike @hassaanfarooq01 I don't see any CI actions running on my recent PR #47. We need to have CI running on schedule and push events in this repo to follow best practices, otherwise we don't know if package releases have introduced bugs or if PRs are potentially introducing bugs.

**Comment by kalenmike** [comment]
@glenn-jocher This is resolved on the develop branch. We are testing there and then we will merge to main.
